---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ovpn-web-connector.fullname" . }}-openvpn-config
  labels:
    {{- include "ovpn-web-connector.labels" . | nindent 4 }}
type: Opaque
data:
    openvpn.ovpn: |
{{ .Values.openvpnConfig | b64enc | indent 8 }}
---
{{- if .Values.secrets -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ovpn-web-connector.fullname" . }}-environment
  labels:
    {{- include "ovpn-web-connector.labels" . | nindent 4 }}
type: Opaque
data:
{{- range $key, $value := .Values.secrets }}
  {{ $key }}: {{ $value | b64enc}}
{{- end }}
{{- end }}
