{{- if .Values.secrets -}}
apiVersion: v1
kind: Secret
metadata:
  annotations:
  name: {{ include "ocker-reegistry-browser.fullname" . }}
  # TODO: Evaluate how to prevent this if to fail in case of no values on metadata.labels
  {{- if or .Values.metadata.labels }}
  labels:
    {{- toYaml .Values.metadata.labels | trimSuffix "\n" | nindent 4 }}
    {{- include "ocker-reegistry-browser.labels" . | nindent 4 }}
  {{- else }}
    {{- include "ocker-reegistry-browser.labels" . | nindent 4 }}
  {{- end }}

type: Opaque
data:
{{- range $key, $value := .Values.secrets }}
  {{ $key }}: {{ $value | b64enc}}
{{- end }}
{{- end }}
